### ISSUE TITLE
problem using checks method

### ISSUE THREAD

**Issue by khorammfar** [quitegreensky/perfectmoney#7]
Hello, I had a few questions about perfect money.

this is my queryset:

`<QueryDict: {'PAYEE_ACCOUNT': ['U123456'], 'PAYMENT_ID': ['NULL'], 'PAYMENT_AMOUNT': ['20'], 'PAYMENT_UNITS': ['USD'], 'PAYMENT_BATCH_NUM': ['12345678'], 'PAYER_ACCOUNT': ['U1234'], 'TIMESTAMPGMT': ['1660559453'], 'V2_HASH': ['HASH-HASH'], 'payment_pk': ['id'], 'BAGGAGE_FIELDS': ['payment_pk']}>`

"checks" It requires a secret. What is that?

and what is "PAYMENT_ID" ? i have to set that in my form?

and why the "PAYMENT_ID" is null? (i pay with my own account in my own gateway)

**Comment by quitegreensky** [comment]
> Hello, I had a few questions about perfect money.
> 
> this is my queryset:
> 
> `<QueryDict: {'PAYEE_ACCOUNT': ['U123456'], 'PAYMENT_ID': ['NULL'], 'PAYMENT_AMOUNT': ['20'], 'PAYMENT_UNITS': ['USD'], 'PAYMENT_BATCH_NUM': ['12345678'], 'PAYER_ACCOUNT': ['U1234'], 'TIMESTAMPGMT': ['1660559453'], 'V2_HASH': ['HASH-HASH'], 'payment_pk': ['id'], 'BAGGAGE_FIELDS': ['payment_pk']}>`
> 
> "checks" It requires a secret. What is that?
> 
> and what is "PAYMENT_ID" ? i have to set that in my form?
> 
> and why the "PAYMENT_ID" is null? (i pay with my own account in my own gateway)

I don't see "checks" or "secret" in the provided data.

According to the official documents: 
> PAYMENT_ID: Optional merchant reference number. If present, this string of up to 50 characters is placed in the transaction. > Payer and/or payee may search/query account history for this value.

You can find the documentations [here](https://perfectmoney.com/documents/perfectmoney-api.doc)

**Comment by khorammfar** [comment]
مستندات رو مطالعه کردم به نتیجه مطلوبی نرسیدم نسخه وردپرسش رو نگاه کردم
دیدم خیلی چیزایی که تو مستندات نگفته بود رو اونجا پیاده کرده بود اونا رو
اعمال کردم اوکی شد
ممنون بابت ریپلی
